### ISSUE TITLE
URGENT: Issue with spelling on <title> tag

### ISSUE THREAD

**Issue by ecarralt** [muktek/homepage#11]
#It reads: "Aprende a progamar y desarrolar software desde cero. MUKTEK"

Should read: "Aprende a programar y desarrollar software desde cero. MUKTEK" (doubl "l" on desarrollar and "r" in programar)

@tphdev

**Comment by ecarralt** [comment]
@tphdev did you get a chance to see this one?

**Comment by tphdev** [comment]
Yes, it's been fixed

**Comment by tphdev** [comment]
![banners_and_alerts_and_view-source_www_muktek_com](https://user-images.githubusercontent.com/7632025/36398393-863c726c-158c-11e8-96b0-90dcdefa3b6e.png)

**Comment by tphdev** [comment]
@ecarralt
