### ISSUE TITLE
Add a menu item for Diplomado

### ISSUE THREAD

**Issue by ecarralt** [muktek/homepage#13]
The two menu items could be:

JavaScript Full-Stack (Full Time)
JavaScript Full-Stack (Diplomado)

The reason for this is feedback that it is hard to find the info for Diplomado. 

@tphdev

**Comment by tphdev** [comment]
![aprende_a_programar_y_desarrollar_software_desde_cero__muktek_and__nav_scss_ ___projects_mhomepage](https://user-images.githubusercontent.com/7632025/36398331-309818c0-158c-11e8-9c6c-906e1d5a09aa.png)

**Comment by tphdev** [comment]
@ecarralt

**Comment by ecarralt** [comment]
Hey @tphdev Thanks. the "Blog" menu item does not show up in 100% zoom in three of our computers. I think we should reopen the issue and adjust font size or something, to allow for this.

**Comment by ecarralt** [comment]
Yep, this is good now. Thank you.
