### ISSUE TITLE
New course dates (URGENT, please)

### ISSUE THREAD

**Issue by ecarralt** [muktek/homepage#15]
Introduccion al Manejo de Datos: March 24th, April 7, 14, 21

Introduccion al Desarrollo Web, Front End: 

a) March 24th, April 7, 14, 21

b) May 19th, May 26th, June 2nd and June 9th

JavaScript Full Stack (Bootcamp): starts July 2nd

JavaScript Full Stack (Diplomado): starts Nov 5th 

@tphdev

**Comment by ecarralt** [comment]
I updated this comment @tphdev

**Comment by ecarralt** [comment]
Hey @tphdev could we update the dates of the JS courses here and other places where they appear?
Thanks!


![screen shot 2018-04-03 at 14 00 40](https://user-images.githubusercontent.com/19524991/38269941-91ef9ab2-3747-11e8-8fb4-016c899cc8ee.png)

**Comment by tphdev** [comment]
@ecarralt just updated these on the main page and on the /cursos/js pages
