### ISSUE TITLE
Need better descripton of FT and Diplomado on Home

### ISSUE THREAD

**Issue by ecarralt** [muktek/homepage#3]
Add the right language to the JS section on the Homepage - 15 semanas + Diplomado (7 meses)

![screen shot 2017-12-09 at 17 07 40](https://user-images.githubusercontent.com/19524991/33800338-98312b1e-dd03-11e7-9e43-4ecdced262ba.png)

**Comment by ecarralt** [comment]
@t3patterson added issue to test this. Sounds like it should work.

**Comment by t3patterson** [comment]
Information for this has been updated, and part time information now w/ link included
![aprende_a_progamar_y_desarrolar_software_desde_cero__muktek](https://user-images.githubusercontent.com/7632025/34007046-10597914-e0c6-11e7-9635-3779f73501db.png)
